version: '3.5'

services:
  
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8083:8080
  
  mysqlsrv:
    container_name: mysqlsrv
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=MySql2021!
      - MYSQL_DATABASE=springdocker01
      - MYSQL_USER=wanderson
      - MYSQL_PASSWORD=MySql2021!
    ports:
      - "3307:3306"
    expose:
      - 3307
    
#  backend:
#    container_name: backend
#    depends_on:
#      - mysqlsrv
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_HOST=mysqlsrv
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=MySql2021!
#      - DATABASE_NAME=springdocker01
#      - DATABASE_PORT=3307
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlsrv:3307/springdocker01?autoReconnect=true&useSSL=false
#      
#  web:
#    container_name: web
#    depends_on:
#      - mysqlsrv
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    image: web:latest
#    ports:
#      - 8090:8080
#    environment: # Pass environment variables to the service
#      - DATABASE_HOST=mysqlsrv
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=MySql2021!
#      - DATABASE_NAME=springdocker01
#      - DATABASE_PORT=3307
#    networks:
#      - errpprime-network
