version: '3.5'

networks : 
  erpprime_net:
    name: erpprime_net

services:
  erpprime_sql_server_db:
    container_name: erpprime_sql_server_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "11433:1433"
    expose:
      - 11433
    environment:
      SA_PASSWORD: "totvs@12345"
      ACCEPT_EULA: "Y"
    networks:
      - erpprime_net
      
  erpprime_web:
    container_name: erpprime_web
    depends_on:
      - erpprime_sql_server_db
    build:
      context: ./
      dockerfile: Dockerfile
    image: erpprime_web:latest
    ports:
      - 8087:8080
    networks:
      - erpprime_net
    
     