version: '3.5'

services:
  
  # Container do mysql, gera o banco de dados no caso definido na variavel MYSQL_DATABASE
  # A String de conexão fica sendo jdbc:mysql://mysqldb:3306/springdocker01
  mysqldb:
    container_name: mysqldb
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springdocker01
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
  
  # Container de backend depende do servidor mysql, a configuração esta no Dockerfile
  # O Dockerfile carrega o arquivo jar gerado para dentro do container
  # A url dessa api fica sendo por exemplo: http://localhost:8080/api/users
  back:
    container_name: erpprimeback
    depends_on:
      - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - mysqldb

  # Administrador de banco de dados mysql, acessa via browser    
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8083:8080
    links:
      - mysqldb

  # Container do Jenkins
  jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
       - 8084:8080
       - 50000:50000
      container_name: jenkins
      volumes:
      - C:/Estudos/jenkins/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock